### ISSUE TITLE
[BUG] 가입 후 첫 로그인 시 가족 코드 생성 모달 개선

### ISSUE THREAD

**Issue by ddooyn** [hwamony/harmony_FE#38]
## Description
가족 코드가 생성된 후 복사하기 전에 dimed 영역 눌러서 모달이 사라지니 다시 생성했을 때 또 다른 코드가 생성되는 문제

## How to fix
- [x] dimed 영역 눌러도 모달 사라지지 않도록 수정
- [x] 실수로 취소를 누르더라도 한번 생성한 뒤엔 똑같은 가족 코드 보여주기

## ETC
해결 방법을 위처럼 생각해봤는데 구현 상황에 맞게 바꿔서 진행해주시면 감사하겠습니다!

**Comment by slozche** [comment]
넵 확인했습니다.
생각해주신 방안 중에서는 두번째가 더 로직에 맞을 것 같습니다. 
아니면 한번 생성된 가족코드는 다른 곳에서도 볼 수 있도록 처리하는 방법과 생선된 가족코드를 보여주는 모달창을 끌 때에는 자동으로 복사가 되도록 로직을 바꾸는 방법도 있을 수 있겠네요!
